{{- range $name := list "agent" "gateway" "cluster" }}
{{- $c := index $.Values $name }}
{{- if $c.enabled }}
{{- $ctx := dict "root" $ "name" $name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-collector.componentFullname" $ctx }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "otel-collector.componentLabels" $ctx | nindent 4 }}
data:
  config.yaml: |
    {{- include "otel-collector.config" $ctx | nindent 4 }}
{{- end }}
{{- end }}
