{{- range $name := list "agent" "gateway" "cluster" }}
{{- $c := index $.Values $name }}
{{- if and $c.enabled $c.serviceAccount.create }}
{{- $ctx := dict "root" $ "name" $name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otel-collector.serviceAccountName" $ctx }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "otel-collector.componentLabels" $ctx | nindent 4 }}
  {{- with $c.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
